-- MySQL Script generated by MySQL Workbench
-- Wed Jul 12 22:44:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EducationDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `EducationDB` ;

-- -----------------------------------------------------
-- Schema EducationDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EducationDB` DEFAULT CHARACTER SET utf8 ;
USE `EducationDB` ;

-- -----------------------------------------------------
-- Table `EducationDB`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Role` (
  `role_id` INT NOT NULL,
  `role_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Sport_Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Sport_Team` (
  `team_id` INT NOT NULL,
  `team_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`team_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Club`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Club` (
  `club_id` INT NOT NULL,
  `club_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`club_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Bank_Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Bank_Account` (
  `bankAcc_id` INT NOT NULL,
  `acc_num` INT NOT NULL,
  `rounting_num` INT NOT NULL,
  PRIMARY KEY (`bankAcc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Credit_Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Credit_Card` (
  `creditCard_id` INT NOT NULL,
  `cc_num` FLOAT NOT NULL,
  `cvv` INT NOT NULL,
  `exp_date` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`creditCard_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Payment_Method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Payment_Method` (
  `payment_method_id` INT NOT NULL,
  `bank_acc` INT NULL,
  `creditCard` INT NULL,
  PRIMARY KEY (`payment_method_id`),
  INDEX `FK_PAYMENTMETHOD_BANKACCOUNT_idx` (`bank_acc` ASC) VISIBLE,
  INDEX `FK_PAYMENTMETHOD_CREDITCARD_idx` (`creditCard` ASC) VISIBLE,
  CONSTRAINT `FK_PAYMENTMETHOD_BANKACCOUNT`
    FOREIGN KEY (`bank_acc`)
    REFERENCES `EducationDB`.`Bank_Account` (`bankAcc_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_PAYMENTMETHOD_CREDITCARD`
    FOREIGN KEY (`creditCard`)
    REFERENCES `EducationDB`.`Credit_Card` (`creditCard_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Institution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Institution` (
  `institution_id` INT NOT NULL,
  `institution_name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`institution_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Administrator` (
  `administrator_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `dob` VARCHAR(45) NOT NULL,
  `register_by` INT NULL,
  PRIMARY KEY (`administrator_id`),
  INDEX `FK_ADMINISTRATOR_ADMINISTRATOR_idx` (`register_by` ASC) VISIBLE,
  CONSTRAINT `FK_ADMINISTRATOR_REGOSTER_BY`
    FOREIGN KEY (`register_by`)
    REFERENCES `EducationDB`.`Administrator` (`administrator_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Semester`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Semester` (
  `semester_id` INT NOT NULL,
  `institution` INT NOT NULL,
  `year` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`semester_id`),
  INDEX `FK_SEMESTER_INSTITUTION_idx` (`institution` ASC) VISIBLE,
  CONSTRAINT `FK_SEMESTER_INSTITUTION`
    FOREIGN KEY (`institution`)
    REFERENCES `EducationDB`.`Institution` (`institution_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Calendar` (
  `calendar_id` INT NOT NULL,
  `semester` INT NOT NULL,
  `holiday_date` VARCHAR(45) NULL,
  `holiday_name` VARCHAR(45) NULL,
  PRIMARY KEY (`calendar_id`),
  INDEX `FK_CALENDAR_SEMESTER_idx` (`semester` ASC) VISIBLE,
  CONSTRAINT `FK_CALENDAR_SEMESTER`
    FOREIGN KEY (`semester`)
    REFERENCES `EducationDB`.`Semester` (`semester_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Student` (
  `student_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `dob` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Staff` (
  `staff_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `dob` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`staff_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Class` (
  `class_id` INT NOT NULL,
  `class_name` VARCHAR(45) NOT NULL,
  `seat_limit` INT NULL,
  `price` DOUBLE NULL,
  PRIMARY KEY (`class_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Major`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Major` (
  `major_id` INT NOT NULL,
  `major_name` VARCHAR(45) NOT NULL,
  `sudent_count` INT NOT NULL,
  PRIMARY KEY (`major_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Department` (
  `department_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `staff_num` INT NULL,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Event` (
  `event_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `location` VARCHAR(500) NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`event_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Book` (
  `book_id` INT NOT NULL,
  `ISBM` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`book_id`, `ISBM`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Subject` (
  `subject_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`subject_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Account` (
  `account_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_num` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`account_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Profile` (
  `profile_id` INT NOT NULL,
  `account` INT NOT NULL,
  `dob` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`profile_id`),
  INDEX `FK_PROFILE_ACCOUNT_idx` (`account` ASC) VISIBLE,
  CONSTRAINT `FK_PROFILE_ACCOUNT`
    FOREIGN KEY (`account`)
    REFERENCES `EducationDB`.`Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Library`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Library` (
  `library_id` INT NOT NULL,
  `institution` INT NOT NULL,
  `lib_name` VARCHAR(45) NOT NULL,
  `Location` VARCHAR(200) NOT NULL,
  `book` INT NOT NULL,
  PRIMARY KEY (`library_id`),
  INDEX `FK_LIBRARY_INSTITUTION_idx` (`institution` ASC) VISIBLE,
  INDEX `FK_LIBRARY_BOOK_idx` (`book` ASC) VISIBLE,
  CONSTRAINT `FK_LIBRARY_INSTITUTION`
    FOREIGN KEY (`institution`)
    REFERENCES `EducationDB`.`Institution` (`institution_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_LIBRARY_BOOK`
    FOREIGN KEY (`book`)
    REFERENCES `EducationDB`.`Book` (`book_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`User_Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`User_Role` (
  `userrole_id` INT NOT NULL,
  `account` INT NOT NULL,
  `role` INT NULL,
  PRIMARY KEY (`userrole_id`),
  INDEX `FK_USERROLE_ROLE_idx` (`role` ASC) VISIBLE,
  INDEX `FK_USERROLE_ACCOUNT_idx` (`account` ASC) VISIBLE,
  CONSTRAINT `FK_USERROLE_ROLE`
    FOREIGN KEY (`role`)
    REFERENCES `EducationDB`.`Role` (`role_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_USERROLE_ACCOUNT`
    FOREIGN KEY (`account`)
    REFERENCES `EducationDB`.`Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Default_Payment_Method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Default_Payment_Method` (
  `default_payment_id` INT NOT NULL,
  `payment_method` INT NOT NULL,
  `student` INT NOT NULL,
  PRIMARY KEY (`default_payment_id`),
  INDEX `FK_DEFAULTPAYMENT_STUDENT_idx` (`student` ASC) VISIBLE,
  INDEX `FK_DEFAULTPAYMENT_PAYMENTMETHOD_idx` (`payment_method` ASC) VISIBLE,
  CONSTRAINT `FK_DEFAULTPAYMENT_STUDENT`
    FOREIGN KEY (`student`)
    REFERENCES `EducationDB`.`Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_DEFAULTPAYMENT_PAYMENTMETHOD`
    FOREIGN KEY (`payment_method`)
    REFERENCES `EducationDB`.`Payment_Method` (`payment_method_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Institutional_Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Institutional_Role` (
  `institutional_role_id` INT NOT NULL,
  `institution` INT NOT NULL,
  `role` INT NULL,
  PRIMARY KEY (`institutional_role_id`),
  INDEX `FK_INSTITUTIONALROLE_INSTITUTION_idx` (`institution` ASC) VISIBLE,
  INDEX `FK_INSTITUTIONALROLE_ROLE_idx` (`role` ASC) VISIBLE,
  CONSTRAINT `FK_INSTITUTIONALROLE_INSTITUTION`
    FOREIGN KEY (`institution`)
    REFERENCES `EducationDB`.`Institution` (`institution_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_INSTITUTIONALROLE_ROLE`
    FOREIGN KEY (`role`)
    REFERENCES `EducationDB`.`Role` (`role_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Qualification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Qualification` (
  `qualification_id` INT NOT NULL,
  `staff` INT NOT NULL,
  `education_level` VARCHAR(45) NOT NULL,
  `school_name` VARCHAR(100) NULL,
  `degree` VARCHAR(45) NULL,
  PRIMARY KEY (`qualification_id`),
  INDEX `FK_QUALIFICATION_STAFF_idx` (`staff` ASC) VISIBLE,
  CONSTRAINT `FK_QUALIFICATION_STAFF`
    FOREIGN KEY (`staff`)
    REFERENCES `EducationDB`.`Staff` (`staff_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Employment_History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Employment_History` (
  `employment_history_id` INT NOT NULL,
  `staff` INT NOT NULL,
  `company_name` VARCHAR(45) NULL,
  `position` VARCHAR(45) NULL,
  `start_year` VARCHAR(45) NULL,
  `end_year` VARCHAR(45) NULL,
  PRIMARY KEY (`employment_history_id`),
  INDEX `FK_EMPLOYMENTHISTORY_STAFF_idx` (`staff` ASC) VISIBLE,
  CONSTRAINT `FK_EMPLOYMENTHISTORY_STAFF`
    FOREIGN KEY (`staff`)
    REFERENCES `EducationDB`.`Staff` (`staff_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Student_Enrollment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Student_Enrollment` (
  `student_enroll_id` INT NOT NULL,
  `student` INT NOT NULL,
  `semester` INT NOT NULL,
  PRIMARY KEY (`student_enroll_id`),
  INDEX `FK_STUDENTENROLLMENT_STUDENT_idx` (`student` ASC) VISIBLE,
  INDEX `FK_STUDENTENROLLMENT_SEMESTER_idx` (`semester` ASC) VISIBLE,
  CONSTRAINT `FK_STUDENTENROLLMENT_STUDENT`
    FOREIGN KEY (`student`)
    REFERENCES `EducationDB`.`Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_STUDENTENROLLMENT_SEMESTER`
    FOREIGN KEY (`semester`)
    REFERENCES `EducationDB`.`Semester` (`semester_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Academic_Record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Academic_Record` (
  `academic_record_id` INT NOT NULL,
  `student` INT NOT NULL,
  `grade_level` VARCHAR(45) NULL,
  `gpa` DOUBLE NULL,
  PRIMARY KEY (`academic_record_id`),
  INDEX `FK_ACADEMICRECORD_STUDENT_idx` (`student` ASC) VISIBLE,
  CONSTRAINT `FK_ACADEMICRECORD_STUDENT`
    FOREIGN KEY (`student`)
    REFERENCES `EducationDB`.`Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Medical_History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Medical_History` (
  `medical_history__id` INT NOT NULL,
  `student` INT NOT NULL,
  `time` VARCHAR(45) NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`medical_history__id`),
  INDEX `FK_MEDICALHISTORY_STUDENT_idx` (`student` ASC) VISIBLE,
  CONSTRAINT `FK_MEDICALHISTORY_STUDENT`
    FOREIGN KEY (`student`)
    REFERENCES `EducationDB`.`Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Course_Enrollment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Course_Enrollment` (
  `course_enroll_id` INT NOT NULL,
  `class` INT NOT NULL,
  `student` INT NOT NULL,
  PRIMARY KEY (`course_enroll_id`),
  INDEX `FK_COURSEENROLLMENT_STUDENT_idx` (`student` ASC) VISIBLE,
  INDEX `FK_COURSEENROLLMENT_CLASS_idx` (`class` ASC) VISIBLE,
  CONSTRAINT `FK_COURSEENROLLMENT_STUDENT`
    FOREIGN KEY (`student`)
    REFERENCES `EducationDB`.`Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_COURSEENROLLMENT_CLASS`
    FOREIGN KEY (`class`)
    REFERENCES `EducationDB`.`Class` (`class_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Major_enrollment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Major_enrollment` (
  `major_enroll_id` INT NOT NULL,
  `major` INT NOT NULL,
  `student` INT NOT NULL,
  PRIMARY KEY (`major_enroll_id`),
  INDEX `FK_MAJORENROLLMENT_MAJOR_idx` (`major` ASC) VISIBLE,
  INDEX `FK_MAJORENROLLMENT_STUDENT_idx` (`student` ASC) VISIBLE,
  CONSTRAINT `FK_MAJORENROLLMENT_MAJOR`
    FOREIGN KEY (`major`)
    REFERENCES `EducationDB`.`Major` (`major_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_MAJORENROLLMENT_STUDENT`
    FOREIGN KEY (`student`)
    REFERENCES `EducationDB`.`Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Staff_Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Staff_Department` (
  `sd_id` INT NOT NULL,
  `staff` INT NOT NULL,
  `department` INT NOT NULL,
  PRIMARY KEY (`sd_id`),
  INDEX `FK_STAFFDEPARTMENT_STAFF_idx` (`staff` ASC) VISIBLE,
  INDEX `FK_STAFFDEPARTMENT_DEPARTMENT_idx` (`department` ASC) VISIBLE,
  CONSTRAINT `FK_STAFFDEPARTMENT_STAFF`
    FOREIGN KEY (`staff`)
    REFERENCES `EducationDB`.`Staff` (`staff_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_STAFFDEPARTMENT_DEPARTMENT`
    FOREIGN KEY (`department`)
    REFERENCES `EducationDB`.`Department` (`department_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Academic_Program`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Academic_Program` (
  `program_id` INT NOT NULL,
  `institution` INT NOT NULL,
  `major` INT NULL,
  `class` INT NULL,
  `subject` INT NULL,
  PRIMARY KEY (`program_id`),
  INDEX `PK_ACADEMICPROGRAM_MAJOR_idx` (`major` ASC) VISIBLE,
  INDEX `PK_ACADEMICPROGRAM_CLASS_idx` (`class` ASC) VISIBLE,
  INDEX `PK_ACADEMICPROGRAM_INSTITUTION_idx` (`institution` ASC) VISIBLE,
  INDEX `PK_ACADEMICPROGRAM_SUBJECT_idx` (`subject` ASC) VISIBLE,
  CONSTRAINT `PK_ACADEMICPROGRAM_MAJOR`
    FOREIGN KEY (`major`)
    REFERENCES `EducationDB`.`Major` (`major_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `PK_ACADEMICPROGRAM_CLASS`
    FOREIGN KEY (`class`)
    REFERENCES `EducationDB`.`Class` (`class_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `PK_ACADEMICPROGRAM_INSTITUTION`
    FOREIGN KEY (`institution`)
    REFERENCES `EducationDB`.`Institution` (`institution_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PK_ACADEMICPROGRAM_SUBJECT`
    FOREIGN KEY (`subject`)
    REFERENCES `EducationDB`.`Subject` (`subject_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Specific_Study`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Specific_Study` (
  `s_study_id` INT NOT NULL,
  `subject` INT NOT NULL,
  `major` INT NOT NULL,
  PRIMARY KEY (`s_study_id`),
  INDEX `FK_SPECIFICSTUDY_SUBJECT_idx` (`subject` ASC) VISIBLE,
  INDEX `FK_SPECIFICSTUDY_MAJOR_idx` (`major` ASC) VISIBLE,
  CONSTRAINT `FK_SPECIFICSTUDY_SUBJECT`
    FOREIGN KEY (`subject`)
    REFERENCES `EducationDB`.`Subject` (`subject_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_SPECIFICSTUDY_MAJOR`
    FOREIGN KEY (`major`)
    REFERENCES `EducationDB`.`Major` (`major_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Member` (
  `member_id` INT NOT NULL,
  `institution` INT NOT NULL,
  `staff` INT NULL,
  `student` INT NULL,
  `administrator` INT NULL,
  PRIMARY KEY (`member_id`),
  INDEX `FK_MEMBER_INSTITUTION_idx` (`institution` ASC) VISIBLE,
  INDEX `FK_MEMBER_STAFF_idx` (`staff` ASC) VISIBLE,
  INDEX `FK_MEMBER_STUDENT_idx` (`student` ASC) VISIBLE,
  INDEX `FK_MEMBER_ADMINISTRATOR_idx` (`administrator` ASC) VISIBLE,
  CONSTRAINT `FK_MEMBER_INSTITUTION`
    FOREIGN KEY (`institution`)
    REFERENCES `EducationDB`.`Institution` (`institution_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_MEMBER_STAFF`
    FOREIGN KEY (`staff`)
    REFERENCES `EducationDB`.`Staff` (`staff_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_MEMBER_STUDENT`
    FOREIGN KEY (`student`)
    REFERENCES `EducationDB`.`Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_MEMBER_ADMINISTRATOR`
    FOREIGN KEY (`administrator`)
    REFERENCES `EducationDB`.`Administrator` (`administrator_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Entertainment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Entertainment` (
  `entertainment_id` INT NOT NULL,
  `institution` INT NOT NULL,
  `event` INT NULL,
  `sport_team` INT NULL,
  `club` INT NULL,
  PRIMARY KEY (`entertainment_id`),
  INDEX `FK_ENTERTAINMENT_INSTITUTION_idx` (`institution` ASC) VISIBLE,
  INDEX `FK_ENTERTAINMENT_EVENT_idx` (`event` ASC) VISIBLE,
  INDEX `FK_ENTERTAINMENT_TEAM_idx` (`sport_team` ASC) VISIBLE,
  INDEX `FK_ENTERTAINMENT_CLUB_idx` (`club` ASC) VISIBLE,
  CONSTRAINT `FK_ENTERTAINMENT_INSTITUTION`
    FOREIGN KEY (`institution`)
    REFERENCES `EducationDB`.`Institution` (`institution_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_ENTERTAINMENT_EVENT`
    FOREIGN KEY (`event`)
    REFERENCES `EducationDB`.`Event` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_ENTERTAINMENT_TEAM`
    FOREIGN KEY (`sport_team`)
    REFERENCES `EducationDB`.`Sport_Team` (`team_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_ENTERTAINMENT_CLUB`
    FOREIGN KEY (`club`)
    REFERENCES `EducationDB`.`Club` (`club_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Subject_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Subject_Type` (
  `subject_type_id` INT NOT NULL,
  `subject` INT NOT NULL,
  `department` INT NOT NULL,
  PRIMARY KEY (`subject_type_id`),
  INDEX `FK_SUBJECTTYPE_SUBJECT_idx` (`subject` ASC) VISIBLE,
  INDEX `FK_SUBJECTTYPE_MAJOR_idx` (`department` ASC) VISIBLE,
  CONSTRAINT `FK_SUBJECTTYPE_SUBJECT`
    FOREIGN KEY (`subject`)
    REFERENCES `EducationDB`.`Subject` (`subject_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_SUBJECTTYPE_DEPARTMENT`
    FOREIGN KEY (`department`)
    REFERENCES `EducationDB`.`Department` (`department_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Class_Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Class_Subject` (
  `class_subject_id` INT NOT NULL,
  `subject` INT NOT NULL,
  `class` INT NOT NULL,
  PRIMARY KEY (`class_subject_id`),
  INDEX `FK_CLASSSUBJECT_SUBJECT_idx` (`subject` ASC) VISIBLE,
  INDEX `FK_CLASSSUBJECT_CLASS_idx` (`class` ASC) VISIBLE,
  CONSTRAINT `FK_CLASSSUBJECT_SUBJECT`
    FOREIGN KEY (`subject`)
    REFERENCES `EducationDB`.`Subject` (`subject_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_CLASSSUBJECT_CLASS`
    FOREIGN KEY (`class`)
    REFERENCES `EducationDB`.`Class` (`class_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`User` (
  `user_id` INT NOT NULL,
  `account` INT NULL,
  `administrator` TINYINT NULL,
  `student` TINYINT NULL,
  `staff` TINYINT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `FK_USER_ACCOUNT_idx` (`account` ASC) VISIBLE,
  CONSTRAINT `FK_USER_ACCOUNT`
    FOREIGN KEY (`account`)
    REFERENCES `EducationDB`.`Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducationDB`.`Division`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducationDB`.`Division` (
  `division_id` INT NOT NULL,
  `department` INT NOT NULL,
  `institution` INT NOT NULL,
  PRIMARY KEY (`division_id`),
  INDEX `FK_DIVISION_DEPARTMENT_idx` (`department` ASC) VISIBLE,
  INDEX `FK_DIVISION_INSTITUTION_idx` (`institution` ASC) VISIBLE,
  CONSTRAINT `FK_DIVISION_DEPARTMENT`
    FOREIGN KEY (`department`)
    REFERENCES `EducationDB`.`Department` (`department_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_DIVISION_INSTITUTION`
    FOREIGN KEY (`institution`)
    REFERENCES `EducationDB`.`Institution` (`institution_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
